// The sim report for the PR (docs/evidence/flt-27/report.md): `LEAPFROG_REPORT=1 pnpm vitest run src/sim/race/leapfrog/report.test.ts`.
// Without the variable it only checks that the report can be built. Not game code.
import { BENCH_BY_ID } from "../../../content/leapfrog";
import { RIVAL_BY_ID, YOU, type RivalId } from "../../../content/rivals";
import { createRng } from "../../rng";
import { createInitialState } from "../../state";
import { perfBudget } from "../../testkit";
import { dailyLeapfrog, enableLeapfrog } from "./driver";
import { runHeadless, type HeadlessReport } from "./headless";
import { leapfrogView } from "./view";

const nameOf = (id: string, lab: string) => (id === YOU ? lab : (RIVAL_BY_ID[id as RivalId]?.short ?? id));
const avg = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);
const f1 = (n: number) => n.toFixed(1);

function board(r: HeadlessReport): string {
  const v = r.view;
  const head = ["Lab", ...v.benchmarks.map((b) => b.short), "wins"];
  const rows = v.rows.map((row) => [
    row.you ? `**${row.short}**` : row.short,
    ...row.scores.map((sc, i) => (sc === null ? "–" : `${row.sota[i] ? "**" : ""}${row.maxx[i] ? "*" : ""}${v.benchmarks[i]!.kind === "elo" ? Math.round(sc) : f1(sc)}${row.sota[i] ? "**" : ""}`)),
    String(row.wins),
  ]);
  return [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`, ...rows.map((x) => `| ${x.join(" | ")} |`)].join("\n");
}

function build() {
  const runs = [1, 2, 3].map((seed) => runHeadless(seed, { days: 365 }));
  const long = [1, 2, 3].map((seed) => ({ on: runHeadless(seed, { days: 700 }), off: runHeadless(seed, { days: 700, off: true }) }));
  const lines: string[] = [];
  lines.push("# FLT-27 sim report: Release Leapfrog", "", "_Headless: the scripted player of `sim/race/leapfrog/headless.ts` (the playthrough bot's build order) plays 365 game days per seed with the pack on. Generated by `report.test.ts`._", "");
  lines.push("## The rhythm (365 days)", "", "| Seed | Lead drops | Answers next day | Avg days between leads | Gaps (min–max) | Forced-response cards | Mishap cards | Benchmarks solved (day) | SOTA claims (benchmaxxed*) | Times a lab owned the cycle |", "|---|---|---|---|---|---|---|---|---|---|");
  for (const r of runs) {
    const mishaps = Object.entries(r.cards).filter(([k]) => k.startsWith("stream:")).reduce((n, [, c]) => n + c, 0);
    lines.push(`| ${r.seed} | ${r.leads} | ${r.pairs} (${Math.round((100 * r.pairs) / r.leads)}%) | ${f1(avg(r.leadGaps))} | ${Math.min(...r.leadGaps)}–${Math.max(...r.leadGaps)} | ${r.cards.shipNow ?? 0} | ${mishaps} | ${r.solved.map((s) => `${BENCH_BY_ID[s.id]!.short} (d${s.day})`).join(", ")} | ${r.sota} (${r.maxxed}) | ${r.owned} |`);
  }
  const r1 = runs[0]!;
  lines.push("", "## First launches, seed 1", "", "| Day | Slot | Lab | Model | SOTA claimed (\\* = benchmaxxed) |", "|---|---|---|---|---|");
  for (const d of r1.drops.slice(0, 14)) lines.push(`| ${d.day} | ${d.slot === "answer" ? "↳ answer" : "lead"} | ${nameOf(d.lab, r1.world.labName)} | ${d.model} | ${d.claims.join(", ")} |`);
  lines.push("", "## The leaderboard on day 365, seed 1 (bold: holds the record)", "", board(r1));
  lines.push("", "Share of voice on day 365, seed 1: " + r1.view.voice.shares.map((s) => `${nameOf(s.id, r1.world.labName)} ${Math.round(s.share * 100)}%`).join(", ") + `. Trust ${Math.round(r1.view.trust)}.`);
  lines.push("", "## Pack on vs off: does it change whether the scenario can be won? (700 days)", "", "| Seed | Off: outcome, Era 2 / Era 3 day, capability | On: outcome, Era 2 / Era 3 day, capability | Models shipped off / on |", "|---|---|---|---|");
  for (const { on, off } of long) {
    const fmt = (r: HeadlessReport) => `${r.outcome}, d${r.eras[1] ?? "–"} / d${r.eras[2] ?? "–"}, ${Math.round(r.finalCapability)}`;
    lines.push(`| ${on.seed} | ${fmt(off)} | ${fmt(on)} | ${off.models} / ${on.models} |`);
  }
  lines.push("", "## What the ticker said (seed 1, days 1–120)", "");
  const s = createInitialState(1);
  void s;
  const w = r1.world;
  void w;
  return { lines, runs };
}

describe("the sim report", () => {
  it("can be built, and (with LEAPFROG_REPORT=1) is written to docs/evidence/flt-27/report.md", async () => {
    const { lines, runs } = build();
    // The ticker sample comes from a fresh run of 120 days so the first weeks are all there (the World keeps the last 50).
    const early = runHeadless(1, { days: 60 });
    lines.push(...early.world.news.slice(-40).map((n) => `- d${n.day}: ${n.text}`));
    const enabled = createInitialState(3);
    enableLeapfrog(enabled);
    const rng = createRng(4);
    const t0 = performance.now();
    for (let d = 1; d <= 365; d++) {
      enabled.day = d;
      dailyLeapfrog(enabled, rng);
    }
    const dailyMs = (performance.now() - t0) / 365;
    const t1 = performance.now();
    for (let i = 0; i < 500; i++) leapfrogView(enabled);
    const viewMs = (performance.now() - t1) / 500;
    lines.push("", "## Cost", "", `- \`dailyLeapfrog\` (calendar, drops, records, voice): **${(dailyMs * 1000).toFixed(0)} µs** a game day, once every 20 ticks.`, `- \`leapfrogView\` (the HUD snapshot part, at about 5 Hz): **${(viewMs * 1000).toFixed(0)} µs**.`, "");
    expect(runs).toHaveLength(3);
    expect(dailyMs).toBeLessThan(perfBudget(1));
    const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;
    if (env?.LEAPFROG_REPORT) {
      const fs = (await import(/* @vite-ignore */ ("node:fs" as string))) as { mkdirSync: (p: string, o: object) => void; writeFileSync: (p: string, t: string) => void };
      fs.mkdirSync("docs/evidence/flt-27", { recursive: true });
      fs.writeFileSync("docs/evidence/flt-27/report.md", lines.join("\n") + "\n");
    }
  }, 120_000);
});
