#!/usr/bin/env node
// Every line a mod can show, as a script a person can read (FLT-101): its buildings, cards (with their leaked
// documents, a Sankey's every label and flow), each arc state's beats and one-click `?moment=arc:` link, headlines and
// thoughts. Text is quoted exactly as written, `{lab}` and all.
//
//   node scripts/mod-script.mjs <mod.json>               # print the script
//   node scripts/mod-script.mjs <mod.json> <doc.md>      # rewrite the part of doc.md between the script markers
import { readFileSync, writeFileSync } from "node:fs";
import { relative } from "node:path";

const START = "<!-- mod-script:start (generated by scripts/mod-script.mjs; edit the mod, then rerun) -->";
const END = "<!-- mod-script:end -->";

const [modPath, docPath] = process.argv.slice(2);
if (!modPath) {
  console.error("usage: node scripts/mod-script.mjs <mod.json> [doc.md]");
  process.exit(2);
}
const mod = JSON.parse(readFileSync(modPath, "utf8"));
const url = `/${relative(process.cwd(), modPath).split("\\").join("/")}`;
const c = mod.content ?? {};
const out = [];
const say = (s = "") => out.push(s);
const q = (s) => `“${s}”`;
const sign = (n) => (n > 0 ? `+${n}` : `${n}`.replace("-", "−"));

say(`**${mod.name}** (\`${mod.id}\` ${mod.version}), by ${mod.author}.`);
say();
say(`> ${mod.description}`);
say();
say(`Load it: \`?mod=${url}\``);

for (const b of c.buildings?.add ?? []) {
  say();
  say(`### Building: ${b.name}`);
  say();
  say(`${b.size?.join("×")} tiles${b.scenery ? ", scenery (nobody visits)" : ""}. Blurb: ${q(b.blurb)}`);
}

const cards = new Map((c.events?.add ?? []).filter((e) => !e.states).map((e) => [e.id, e]));

/** A Sankey's columns, as the game lays them out: a node sits one column after the deepest node that flows into it. */
function columnsOf(doc) {
  const depth = new Map(doc.nodes.map((n) => [n.id, n.column ?? 0]));
  for (let pass = 0; pass < doc.nodes.length; pass++) {
    for (const f of doc.flows) if (depth.has(f.from) && depth.has(f.to)) depth.set(f.to, Math.max(depth.get(f.to), depth.get(f.from) + 1));
  }
  return depth;
}

function sankey(doc) {
  const name = new Map(doc.nodes.map((n) => [n.id, n.label]));
  const depth = columnsOf(doc);
  const total = (id) => Math.max(doc.flows.filter((f) => f.to === id).reduce((t, f) => t + f.value, 0), doc.flows.filter((f) => f.from === id).reduce((t, f) => t + f.value, 0));
  say(`Units: ${q(doc.units)}. Columns: ${doc.columns.map(q).join(", ")}.`);
  say();
  say("| Column | Node | Sub-label | Total |");
  say("| --- | --- | --- | --- |");
  for (const n of [...doc.nodes].sort((a, b) => depth.get(a.id) - depth.get(b.id))) {
    say(`| ${doc.columns[depth.get(n.id)] ?? depth.get(n.id)} | ${n.label} | ${n.sub ?? ""} | ${total(n.id)} |`);
  }
  say();
  say("Flows:");
  say();
  for (const f of doc.flows) say(`- ${name.get(f.from)} → ${name.get(f.to)}: ${f.value} ${doc.units}`);
}

function card(e) {
  say();
  say(`### Card: ${e.title}`);
  say();
  say(`\`${e.id}\`${e.kind ? `, a ${e.kind} card` : ""}. Stripe: ${q(e.stripe)}.`);
  say();
  say(e.body);
  const d = e.doc;
  if (d) {
    say();
    say(`**Document** (${d.style}): ${[d.app && `app ${q(d.app)}`, d.file && `file ${q(d.file)}`, d.subject && `subject ${q(d.subject)}`, d.from && `from ${q(d.from)}`, d.to && `to ${q(d.to)}`].filter(Boolean).join(", ")}.`);
    say();
    if (d.style === "sankey") sankey(d);
    if (d.lines?.length) {
      say();
      for (const l of d.lines) say(`> ${l}`);
    }
    if (d.sign) {
      say();
      say(`Signed: ${q(d.sign)}`);
    }
  }
  say();
  e.choices.forEach((ch, i) => say(`${i + 1}. **${ch.label}**: ${ch.hint ?? ""}`));
}

/** One verb as a line of the script. */
function beat(a) {
  const p = a.params ?? {};
  switch (a.type) {
    case "toast": return `Toast: ${q(p.text)}`;
    case "news": return `Ticker: ${q(p.text)}`;
    case "camera.beat": return `Camera beat (${p.kind}) on ${p.on}: ${p.kicker ? `kicker ${q(p.kicker)}, ` : ""}caption ${q(p.caption)}${p.sub ? `, sub ${q(p.sub)}` : ""}`;
    case "camera.focus": return `Camera looks at the ${p.on}`;
    case "card": return `Opens the card ${q(cards.get(p.id)?.title ?? p.id)}`;
    case "building.ensure": return `The ${p.kind} appears beside the gate if missing${p.text ? `: ${q(p.text)}` : ""}`;
    case "building.lights": return p.off ? `The ${p.building}'s lights go off for ${p.hours ?? 8} hours` : `The ${p.building}'s lights come back on`;
    case "building.prop": return `A ${p.prop} hangs on the ${p.building} door for ${p.hours ?? 24} hours`;
    case "birdapp.post": return `Bird App, a ${p.archetype} poster (${p.outcome}): ${q(p.text)}`;
    case "birdapp.rival": return `Bird App, a rival lab's ${p.role} (${p.outcome}): ${q(p.text)}`;
    case "sound.cue": return `Sound: ${p.cue}`;
    case "vibes.delta": case "hype.delta": case "trust.delta": return `${a.type.split(".")[0][0].toUpperCase()}${a.type.split(".")[0].slice(1)} ${sign(p.amount)}`;
    default: return `${a.type} ${JSON.stringify(p)}`;
  }
}

const guard = (g) => (!g ? "" : g.type === "after" ? ` after ${g.params.days} day${g.params.days === 1 ? "" : "s"}` : g.type === "choice" ? `: ${q(cards.get(g.params.card)?.choices[+g.params.is]?.label ?? g.params.is)}` : ` (${g.type})`);
const list = (x) => (x === undefined ? [] : Array.isArray(x) ? x : [x]);

for (const arc of [...(c.arcs?.add ?? []), ...(c.events?.add ?? []).filter((e) => e.states)]) {
  say();
  say(`## The story: \`${arc.id}\``);
  say();
  say(`Every state has a one-click link that stages it on a busy lab: \`?mod=${url}&moment=arc:${arc.id}:<state>\`.`);
  for (const [id, st] of Object.entries(arc.states)) {
    say();
    say(`### ${id}${st.type === "final" ? " (the end)" : ""}`);
    say();
    say(`\`?mod=${url}&moment=arc:${arc.id}:${id}\``);
    const entry = list(st.entry);
    if (entry.length) {
      say();
      for (const a of entry) say(`- ${beat(a)}`);
    }
    for (const [ev, ts] of Object.entries(st.on ?? {})) {
      for (const t of list(ts)) {
        const tr = typeof t === "string" ? { target: t } : t;
        say();
        say(`On ${ev}${guard(tr.guard)} → **${tr.target}**${list(tr.actions).length ? ":" : ""}`);
        for (const a of list(tr.actions)) say(`  - ${beat(a)}`);
      }
    }
  }
}

if (cards.size) say();
if (cards.size) say("## Cards");
for (const e of cards.values()) card(e);

if (c.headlines?.add?.length) {
  say();
  say("## Headlines (the ticker, any day)");
  say();
  for (const h of c.headlines.add) say(`- ${h.text}`);
}
if (c.thoughts?.add?.length) {
  say();
  say("## Thoughts (over people's heads)");
  say();
  for (const t of c.thoughts.add) say(`- ${t.kind}, ${t.when}: ${q(t.text)}`);
}

const script = out.join("\n");
if (!docPath) console.log(script);
else {
  const doc = readFileSync(docPath, "utf8");
  const a = doc.indexOf(START), b = doc.indexOf(END);
  if (a < 0 || b < a) {
    console.error(`${docPath}: no script markers; add\n${START}\n${END}`);
    process.exit(1);
  }
  writeFileSync(docPath, `${doc.slice(0, a + START.length)}\n\n${script}\n\n${doc.slice(b)}`);
  console.log(`${docPath}: script rewritten from ${modPath}`);
}
